// <auto-generated />
using CsharpAPI;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CsharpAPI.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20230627163741_First")]
    partial class First
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.19")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("CsharpAPI.Class.Localites", b =>
                {
                    b.Property<int>("IdLocalite")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdLocalite"), 1L, 1);

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdLocalite");

                    b.ToTable("Localites");

                    b.HasData(
                        new
                        {
                            IdLocalite = 1,
                            Nom = "Paris"
                        },
                        new
                        {
                            IdLocalite = 2,
                            Nom = "Lyon"
                        },
                        new
                        {
                            IdLocalite = 3,
                            Nom = "Marseille"
                        });
                });

            modelBuilder.Entity("CsharpAPI.Class.Personnes", b =>
                {
                    b.Property<int>("IdPersonnes")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdPersonnes"), 1L, 1);

                    b.Property<int>("IdLocalite")
                        .HasColumnType("int");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdPersonnes");

                    b.HasIndex("IdLocalite");

                    b.ToTable("Personnes");

                    b.HasData(
                        new
                        {
                            IdPersonnes = 1,
                            IdLocalite = 1,
                            Nom = "Alice"
                        },
                        new
                        {
                            IdPersonnes = 2,
                            IdLocalite = 2,
                            Nom = "Bob"
                        },
                        new
                        {
                            IdPersonnes = 3,
                            IdLocalite = 3,
                            Nom = "Charlie"
                        });
                });

            modelBuilder.Entity("CsharpAPI.Class.Personnes", b =>
                {
                    b.HasOne("CsharpAPI.Class.Localites", "Localite")
                        .WithMany("Personnes")
                        .HasForeignKey("IdLocalite")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Localite");
                });

            modelBuilder.Entity("CsharpAPI.Class.Localites", b =>
                {
                    b.Navigation("Personnes");
                });
#pragma warning restore 612, 618
        }
    }
}
