// <auto-generated />
using CsharpAPI;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CsharpAPI.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20230627092434_MyFirstMigration")]
    partial class MyFirstMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.19")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("CsharpAPI.Class.Localites", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Localites");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Nom = "Paris"
                        },
                        new
                        {
                            Id = 2,
                            Nom = "Lyon"
                        },
                        new
                        {
                            Id = 3,
                            Nom = "Marseille"
                        });
                });

            modelBuilder.Entity("CsharpAPI.Class.Personnes", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("LocaliteId")
                        .HasColumnType("int");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("LocaliteId");

                    b.ToTable("Personnes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            LocaliteId = 1,
                            Nom = "Alice"
                        },
                        new
                        {
                            Id = 2,
                            LocaliteId = 2,
                            Nom = "Bob"
                        },
                        new
                        {
                            Id = 3,
                            LocaliteId = 3,
                            Nom = "Charlie"
                        });
                });

            modelBuilder.Entity("CsharpAPI.Class.Personnes", b =>
                {
                    b.HasOne("CsharpAPI.Class.Localites", "Localite")
                        .WithMany("Personnes")
                        .HasForeignKey("LocaliteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Localite");
                });

            modelBuilder.Entity("CsharpAPI.Class.Localites", b =>
                {
                    b.Navigation("Personnes");
                });
#pragma warning restore 612, 618
        }
    }
}
