// <auto-generated />
using System;
using CsharpAPI;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CsharpAPI.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.19")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("CsharpAPI.Class.Localites", b =>
                {
                    b.Property<Guid>("IdLocalite")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdLocalite");

                    b.ToTable("Localites");

                    b.HasData(
                        new
                        {
                            IdLocalite = new Guid("f61c2588-7332-4d3d-933f-c5b6626cdf8f"),
                            Nom = "Paris"
                        },
                        new
                        {
                            IdLocalite = new Guid("47ce056c-bf60-4063-a6f0-cc7f3264258a"),
                            Nom = "Lyon"
                        },
                        new
                        {
                            IdLocalite = new Guid("04a1a972-c599-4dd6-b375-545c78b60488"),
                            Nom = "Marseille"
                        });
                });

            modelBuilder.Entity("CsharpAPI.Class.Personnes", b =>
                {
                    b.Property<Guid>("IdPersonne")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("LocaliteId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdPersonne");

                    b.HasIndex("LocaliteId");

                    b.ToTable("Personnes");

                    b.HasData(
                        new
                        {
                            IdPersonne = new Guid("55441b1f-8ba6-4739-af30-5dbd02b33912"),
                            LocaliteId = new Guid("f61c2588-7332-4d3d-933f-c5b6626cdf8f"),
                            Nom = "Alice"
                        },
                        new
                        {
                            IdPersonne = new Guid("4757fdf6-d856-409c-a3b7-1dda24b26f33"),
                            LocaliteId = new Guid("47ce056c-bf60-4063-a6f0-cc7f3264258a"),
                            Nom = "Bob"
                        },
                        new
                        {
                            IdPersonne = new Guid("d82d04b9-f35a-40c8-ad71-2a7e1b3e8b70"),
                            LocaliteId = new Guid("04a1a972-c599-4dd6-b375-545c78b60488"),
                            Nom = "Charlie"
                        });
                });

            modelBuilder.Entity("CsharpAPI.Class.Personnes", b =>
                {
                    b.HasOne("CsharpAPI.Class.Localites", "Localite")
                        .WithMany()
                        .HasForeignKey("LocaliteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Localite");
                });
#pragma warning restore 612, 618
        }
    }
}
